### ISSUE TITLE
`STORAGES` setting from Django 4.2

### ISSUE THREAD

**Issue by adamchainz** [adamchainz/django-upgrade#318]
### Description

Combine `DEFAULT_FILE_STORAGE` and `STATICFILES_STORAGE` into a new `STORAGES` dict setting, using `BACKEND`. Put `STORAGES` at the location of the first found setting. Only do it if the values are both plain strings, to avoid oredring issues.

**Comment by GitRon** [comment]
Hi @adamchainz 

I just read in your blog that this tool would fix the `STORAGES` settings. Actually, it's not doing anything in my case and I can't find the error...

````python
# settings.py
STATIC_ROOT = env('DJANGO_STATIC_ROOT')
STATIC_URL = '/static/'
STATICFILES_STORAGE = 'apps.core.manifests.WhiteNoiseStaticFilesStorage'
````

.pre-commit.yml

````yml
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.13.0
    hooks:
      - id: django-upgrade
        args: [--target-version, "4.2"]
        language_version: python3.11
        stages: [ push ]
````

`pre-commit` is just running it and says, everything is great...

> django-upgrade...........................................................Passed

Is there anything I am doing wrong?

Thx!  
Ronny
